[package]
name = "dap-types"
version = "0.0.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
serde = "1.0.213"
serde_json = "1.0.132"
serde_derive = "1.0.213"
foldhash = "0.2.0"
