[package]
name = "dap-types"
version = "0.0.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2018"

[dependencies]
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
ahash = "0.7.6"
