[workspace]
members = [
    "crates/builtins-proc-macro",
    "crates/dm-langserver",
    "crates/dmdoc",
    "crates/dmm-tools",
    "crates/dmm-tools-cli",
    "crates/dreamchecker",
    "crates/dreammaker",
    "crates/interval-tree",
    #"crates/spaceman-dmm",
]

[profile.dev]
opt-level = 2

[profile.release]
lto = true
