[package]
name = "dreammaker"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[lib]
path = "lib.rs"

[dependencies]
interval-tree = { path = "../interval-tree" }
petgraph = { version = "0.4.9", default-features = false }
linked-hash-map = "0.5.0"
lodepng = "2.1.5"
bitflags = "1.0.3"
termcolor = "1.0.4"
ordered-float = "1.0.2"
guard = "0.5.0"

[dev-dependencies]
walkdir = "2.0.1"
