[package]
name = "dreamchecker"
version = "1.7.1"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2018"

[dependencies]
dreammaker = { path = "../dreammaker" }
guard = "0.5.0"
serde_json = "1.0"
ahash = "0.7.6"

[build-dependencies]
chrono = "0.4.0"
git2 = { version = "0.13", default-features = false }
