[package]
name = "dreamchecker"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
dreammaker = { path = "../dreammaker" }
serde_json = "1.0"
foldhash = "0.2.0"

[build-dependencies]
chrono = "0.4.38"
git2 = { version = "0.20.4", default-features = false }
