[package]
name = "dmdoc"
version = "1.4.1"
authors = ["Tad Hardesty <tad@platymuus.com>"]
homepage = "https://github.com/SpaceManiac/SpacemanDMM/blob/master/crates/dmdoc/README.md"
edition = "2018"

[dependencies]
dreammaker = { path = "../dreammaker" }
pulldown-cmark = "0.9.1"
tera = "1.15.0"
serde = "1.0.136"
serde_derive = "1.0.136"
walkdir = "2.3.2"
git2 = { version = "0.14.2", default-features = false }

[dev-dependencies]
walkdir = "2.3.2"

[build-dependencies]
chrono = "0.4.19"
git2 = { version = "0.14.2", default-features = false }
