[package]
name = "dmdoc"
version = "1.7.3"
authors = ["Tad Hardesty <tad@platymuus.com>"]
homepage = "https://github.com/SpaceManiac/SpacemanDMM/blob/master/crates/dmdoc/README.md"
edition = "2018"

[dependencies]
dreammaker = { path = "../dreammaker" }
pulldown-cmark = "0.9.2"
tera = "1.17.0"
serde = "1.0.144"
serde_derive = "1.0.144"
walkdir = "2.3.2"
git2 = { version = "0.16.1", default-features = false }

[dev-dependencies]
walkdir = "2.3.2"

[build-dependencies]
chrono = "0.4.22"
git2 = { version = "0.16.1", default-features = false }
