[package]
name = "dm-langserver"
version = "0.0.1"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[[bin]]
name = "dm-langserver"
path = "main.rs"

[dependencies]
url = "1.6.0"
serde = "1.0.27"
serde_json = "1.0.10"
jsonrpc-core = "8.0.1"
languageserver-types = "0.30"
dreammaker = { path = "../dreammaker" }
petgraph = { version = "0.4.9", default-features = false }
