[package]
name = "dm-langserver"
version = "0.0.1"
authors = ["Tad Hardesty <tad@platymuus.com>"]

[[bin]]
name = "dm-langserver"
path = "main.rs"

[dependencies]
url = "1.6.0"
serde = "1.0.27"
serde_json = "1.0.10"
serde_derive = "1.0.27"
jsonrpc-core = "8.0.1"
languageserver-types = "0.41"
dreammaker = { path = "../dreammaker" }
interval-tree = { path = "../interval-tree" }
petgraph = { version = "0.4.9", default-features = false }

[build-dependencies]
chrono = "0.4.0"
git2 = { version = "0.8", default-features = false }
