[package]
name = "dmm-tools"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2018"

[dependencies]
inflate = "0.4.1"
ndarray = "0.15.3"
rand = "0.8.4"
dreammaker = { path = "../dreammaker" }
lodepng = "3.0.0"
indexmap = "1.7.0"
ahash = "0.7.6"

[dependencies.bytemuck]
version = "1.5"
features = ["derive"]

[dependencies.bumpalo]
version = "3.0.0"
features = ["collections"]

[dependencies.png]
version = "0.17.2"
optional = true

[dependencies.gfx_core]
version = "0.9.2"
optional = true

[dev-dependencies]
walkdir = "2.0.1"
